### PR TITLE
Issue #125: add test for nifti file loader

### LINKED ISSUE #125: Test + docs: dataset/loader/nifti_loader
# Issue description 

Expand unit tests for nifti_loader, in pytest style.

- class NiftiFileLoader
    - init, get_data, get_data_ids, get_num_images, set_group_structure, close

## Type of Issue

Please delete options that are not relevant.

- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests that cover class and methods, asserting that methods return values that are expected for each method.

### PR DESCRIPTION
**Pull request by s-sd**
# Description

test for nifti file loader added

Fixes #125 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
ran tests locally to check

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by NMontanaBrown** [comment]
Hi @s-sd , thanks for the PR! Do you think you could add tests for lines [29-30 ](https://github.com/ucl-candi/DeepReg/blob/6a9bcd3d6de3773446f99c79970d9fe0c1e14c82/deepreg/dataset/loader/nifti_loader.py#L28)?

These lines aren't covered as shown by codecov here:
https://codecov.io/gh/ucl-candi/DeepReg/pull/156/changes

After this I can PR and merge :)

**Comment by s-sd** [comment]
@NMontanaBrown, I've realised that the test for these lines is also missing in the h5 loader test. Should I add it in this same PR or open up a new issue and add it separately?

**Comment by NMontanaBrown** [comment]
Hi @s-sd, I realised I was not the clearest in my request, sorry, one last change! Can we add some explicit assertion error tests for lines 
[30 onwards ](https://github.com/ucl-candi/DeepReg/blob/6a9bcd3d6de3773446f99c79970d9fe0c1e14c82/deepreg/dataset/loader/nifti_loader.py#L30)?

```
assert 0 <= group_index < len(self.group_ids)
 assert 0 <= sample_index
 assert sample_index < len(
self.group_sample_dict[self.group_ids[group_index]]
 )
```
So we would expect an error if tuple (-1, len(self.group_ids)+1) were passed to the loader for the get data method. Could you add tests like these for various cases (out of bounds indices) for these three statements and then the files should be 100% covered if I am not mistaken? 😄

**Comment by s-sd** [comment]
@NMontanaBrown, I'll add these tests now. Is there a way to check codecov before the commit or maybe some way to view it after pushing?

**Comment by NMontanaBrown** [comment]
@s-sd Do you have access to the following link? [codecov](https://codecov.io/gh/ucl-candi/DeepReg/commits)

It may just be me with access, so, alternatively, you can use the following command on terminal/bash to check what statements are missing:
`pytest --cov-report term-missing --cov=deepreg test_file_name.py`

If you run this in the test/unit/ subdir, it should show the coverage for all of deepreg with the lines missing to be tested when the test_file_name.py is run. Just focus on the loaders you have been working on and it should point you to the lines remaining to be covered

**Comment by s-sd** [comment]
@NMontanaBrown, Thank you! The link works. I'll use that but if it doesn't work or update, I'll use the command

**Comment by s-sd** [comment]
@NMontanaBrown, for line 49 (reshape array or squeeze) a test case is not available in the test data. The arrays have been saved after being squeezed. Should I skip this line? Or should I modify one of the test examples?

**Comment by s-sd** [comment]
@NMontanaBrown, for now I have left the demo data as is. If you think that modifying one example from the data is fine then let me know and I'll make the change. Other than that I have now added the tests for the assert statements.

**Comment by NMontanaBrown** [comment]
@s-sd Is it a big hassle to generate a new file to test this case? I wouldn't modify existing cases but perhaps add a file for this test explicitly.

**Comment by s-sd** [comment]
@NMontanaBrown, It won't be too difficult to generate data for this case (I think just doing expand_dims on one of the cases and resaving should be fine). To cover this line in both loaders, we would need both h5 and nifti data for this case which would mean that a new directory under data would be needed. Do you think adding 'data/test/dummy_data/case1.nii.gz' and 'data/test/dummy_data/case1.h5' would be fine or should we skip this line since this is quite different to the directory structure currently used?

**Pull request merged**
