### PR TITLE
#11 learn2reg t2 demo added

### LINKED ISSUE #11: Demo - CT Lung (learn2reg t2)
CT Lung Registration
data: https://zenodo.org/record/3835682#.XuVJ-0BFzx8
https://learn2reg.grand-challenge.org/Dataset/

This demo can test:
1 - unpaired inter-subject reg with/without labels
2 - unpaired intra-subject reg with/without labels
and potentially
3 - paired intra-subject reg with/without labels

### PR DESCRIPTION
**Pull request by s-sd**
# Description

The learn2reg t2 demos have been added

Fixes #11

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- Ran all the scripts to check they work as intended (unit test not added because the functions that are created are only used within the script itself)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (no new tests added as described above)
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by YipengHu** [comment]
@s-sd can you rename the folder to something like: unpaired_ct_lung and paired_lung_ct?

https://github.com/ucl-candi/DeepReg/wiki/Demo-minimum-requirement

**Comment by s-sd** [comment]
@YipengHu 
I have fixed the directory structure for the two demos by putting them in separate folders, renamed the folders and config files and added the scaling part to demo_data.py

I think for the intensity scaling maybe it'll be more user friendly to feed in two values to the generator that can be used to rescale on the fly. But rescaling during the data preparation stage is not too difficult either so I'm not sure what the best strategy would be

**Comment by YipengHu** [comment]
@s-sd Looks good - last thing before we can merge this: can you update both README, so at least it has different demo names and they won;t get confusing. As discussed, we will make an effort later to make all the demos have a consistent "feel" later.

**Comment by s-sd** [comment]
@YipengHu 
I am fixing some linting issues will then merge afterwards

**Comment by mathpluscode** [comment]
for  image-wise intensity scaling, i think we can make this an option in preprocess, where is the code ? can you point me to the function?

**Comment by YipengHu** [comment]
> for image-wise intensity scaling, i think we can make this an option in preprocess, where is the code ? can you point me to the function?

the code is very ad hoc, but the key idea is simple, just rescale it to [0, 1] or [0, 255] or unit-variance with zero-mean

**Comment by YipengHu** [comment]
@s-sd this has not been merged - why is this deleted?

**Pull request closed without merging**
