### PR TITLE
Issue #36 testing pre-commit

### PR DESCRIPTION
**Pull request by YipengHu**
# Description
Some suggested config changes related to #77 

Fixes # (issue)

## Type of change

doc update

# How Has This Been Tested?
n/a

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mathpluscode** [comment]
The rename from similarity to dissimilarity in the config is not done yet in the code

**Comment by YipengHu** [comment]
> The rename from similarity to dissimilarity in the config is not done yet in the code

No. There are a few changes that have not been reflected in code. I would like to list them in the tutorial so you can have a review. I think it is best to merge this tutorial change first - think it is the product specs ;) 

When you finish the multi-folder update #77 , you are likely do adopt and/or adapt some of these. So, with a merged version, we will likely to save some conflicts in links/names. Afterwards, I will do an overall refactoring for all these config options.

**Comment by mathpluscode** [comment]
@YipengHu ok ;)

**Comment by mathpluscode** [comment]
sorry, due to my fault, this branch is too old to be merged.

most of the modifications have been pushed into branch 84 manually,

the rest is requested in https://github.com/ucl-candi/DeepReg/issues/86, asking for corresponding code changes.

this issue will be closed

**Pull request closed without merging**
